using System.Collections.Generic;

namespace RatGame.EditorTools
{
    /// <summary>임시 영어 번역 2 — 결과 화면·로딩 팁부터 (고양이 195). 목록 1이 300줄에 닿아 나눔. 둘 다 LocalizeMenus가 표에 넣는다.</summary>
    public static partial class LocalizationTools
    {
        private static readonly Dictionary<string, string> DummyEn2 = new()
        {
            // 결과 화면
            ["다음 맵으로"] = "to the next map",
            ["기지로"] = "to base",
            ["굶었다..."] = "Starved...",
            ["스테이지 {0}에서 전원 쓰러짐 — 처음부터 다시"] = "Everyone went down on stage {0} — back to the start",
            ["배불리 겨울을 났다!"] = "A well-fed winter!",
            ["스테이지 {0}개를 모두 넘어 가족이 굶지 않았어요 — 엔딩\n이번 런: 모은 식량 {1} · 상점에서 산 물건 {2}개"] = "You cleared all {0} stages and the family didn't starve — ending\nThis run: food gathered {1} · items bought {2}",
            ["스테이지 {0} 클리어!"] = "Stage {0} clear!",
            ["가족이 {0}만큼 먹었어요 — 남은 식량 {1}"] = "The family ate {0} — food left {1}",
            ["무사히 이사 완료!"] = "Made it home safe!",
            ["고양이 밥이 되었다..."] = "Became cat food...",
            ["전원 쥐구멍 집합 — 오늘 수확을 기지로 옮겼어요"] = "Everyone made it to the mousehole — today's haul is at base",
            ["전원 다운 — 이번 적립을 잃었어요 (누계는 그대로)"] = "Everyone went down — this run's stash is lost (total unchanged)",
            ["창고 적립"] = "Stashed in storeroom",
            ["쥐구멍 적립"] = "Stashed in mousehole",
            ["이번 수확"] = "This haul",
            ["잃은 적립"] = "Stash lost",
            [" · 구조 {0}"] = " · rescues {0}",
            ["{0:0}초 뒤 {1}"] = "{1} in {0:0}s",
            ["{0} {1} ({2}개)"] = "{0} {1} ({2})",
            ["들고 옴 {0}"] = "Carried {0}",
            ["이번에 새로 채운 도감은 없어요"] = "No new codex entries this time",
            // 로딩 팁 (LoadingTipsSO)
            ["웅크리면 발소리가 나지 않아요. 고양이 근처에선 기어가세요."] = "Crouching makes no footsteps. Crawl near cats.",
            ["계란은 던지면 깨져요. 굴려서 쥐구멍에 넣으세요."] = "Eggs break when thrown. Roll them into the mousehole.",
            ["쥐구멍에 넣은 물건은 안전해요. 전멸하면 이번 적립은 잃어요."] = "Items in the mousehole are safe. If everyone goes down, this run's stash is lost.",
            ["무거운 건 여럿이 같이 들면 움직여요."] = "Heavy things move when several rats lift together.",
            ["어두운 곳에선 고양이 시야가 절반이 돼요."] = "In the dark, cats see only half as far.",
            ["쓰러진 동료를 쥐구멍까지 옮기면 다시 일어나요."] = "Carry a downed teammate to the mousehole and they get back up.",
            ["끈끈이에 붙은 동료는 [E]를 길게 눌러 구출하세요."] = "Hold [E] to free a teammate stuck on a glue trap.",
            ["곧게 달리면 고양이보다 빨라요. 막다른 길만 피하세요."] = "Running straight outpaces cats. Just avoid dead ends.",
            // 알림 토스트 (고양이 196) — 알림 칸 522×56·최소 17: 이어 붙는 조합(머리줄+오늘, 역할 셋, 쓰러짐 두 줄)이 넘쳐 줄임 (고양이 198)
            ["스테이지 {0}/{1} — 식량 {2} 모아 목적지(주황 방)로"] = "Stage {0}/{1} — bring {2} food to the orange room",
            ["\n오늘: {0}"] = "\nToday: {0}",
            ["문지기(푸른 회색)가 목적지 앞"] = "Gatekeeper (blue-gray) at the goal",
            ["순찰꾼(적갈색)이 큰길을 오감"] = "Patroller (red-brown) roams the hall",
            ["아기는 들키면 엄마를 부름"] = "Kittens call mom if they see you",
            ["막다른 방 하나는 보물방 — 비싼 음식, 함정 가득"] = "One dead end is a treasure room — pricey food, lots of traps",
            ["회색 배관은 쥐만 · "] = "Gray pipes are rats-only · ",
            ["R 킁킁 = 목적지·음식 냄새 · Tab 지도"] = "R sniff = destination & food scent · Tab map",
            ["정전 (어두운 방이 많아요)"] = "Blackout (many dark rooms)",
            ["덫 대방출 (함정이 많아요)"] = "Trap sale (many traps)",
            ["고양이 간식 날 (고양이가 느릿느릿)"] = "Cat treat day (slow cats)",
            ["집주인 외출 (집주인 사건 없음)"] = "Owner's out (no owner events)",
            ["분주한 집 (집주인 사건이 잦아요)"] = "Busy house (many owner events)",
            ["고양이 손님 (한 마리 더 왔어요)"] = "Cat guest (+1 cat)",
            ["냠냠 — 스태미나 +{0:0}"] = "Yum — stamina +{0:0}",
            ["방울 달았다! Tab 지도에 고양이가 보여요"] = "Belled! The cat now shows on the Tab map",
            ["쥐덫 위 음식은 미끼 — 웅크리고(Ctrl) 집기"] = "Food on a mousetrap is bait — crouch (Ctrl) to grab it",
            ["살금살금 — 미끼만 쏙!"] = "Sneaky — bait snatched!",
            ["탁! 미끼는 웅크리고(Ctrl) 살금살금"] = "Snap! Crouch (Ctrl) and sneak for bait",
            ["멀리서 \"나비야~ 간식!\""] = "From afar: \"Kitty~ treats!\"",
            ["고양이가 나갔다! 지금이야"] = "The cat left! Go now",
            ["고양이가 돌아왔다… 어느 문으로?"] = "The cat is back… through which door?",
            ["딩동! 누가 초인종을…"] = "Ding-dong! Someone's at the door…",
            ["집주인이 현관으로 — 고양이도 따라갔다!"] = "The owner went to the door — the cat followed!",
            ["덜컹 — 집주인이 창문을 연다"] = "Clunk — the owner opens a window",
            ["바람! 냄새가 날아가고 가벼운 물건이 굴러간다"] = "Wind! Scents blow away and light things roll",
            ["창문 닫힘"] = "Window closed",
            ["쿵쿵 — 집주인 발소리, 어두운 방에 불이 켜진다"] = "Thud thud — the owner's steps; lights coming on in dark rooms",
            ["딸깍 — 불 켜짐! 어둠이 사라졌다"] = "Click — lights on! The darkness is gone",
            ["불 꺼짐 — 다시 어둠"] = "Lights off — dark again",
            ["리모컨 딸깍 — TV가 켜졌다"] = "Remote click — the TV is on",
            ["고양이가 TV 앞에 앉았다 — 등 뒤로 지나가"] = "The cat sat in front of the TV — sneak behind it",
            ["TV 꺼짐"] = "TV off",
            ["삐— 로봇청소기가 켜졌다"] = "Beep — the robot vacuum started",
            ["청소기 소리에 발소리가 묻힌다 — 지금 뛰어!"] = "The vacuum drowns out footsteps — run now!",
            ["청소기 멈춤 — 다시 조용히"] = "Vacuum stopped — quiet again",
            ["벽 속에서 우르릉 — 배관에 물이 내려온다"] = "Rumbling in the walls — water is coming down the pipes",
            ["쏴아— 배관 안이면 흠뻑 젖는다 (물소리에 발소리가 묻힘)"] = "Whoosh — you'll get soaked in the pipes (water hides footsteps)",
            ["물소리 멈춤"] = "Water stopped",
            ["벽 너머 딸깍딸깍 — 집주인이 덫을 놓는다"] = "Click-click beyond the wall — the owner is setting traps",
            ["새 덫이 생겼다 — 지나온 길도 조심"] = "New traps — watch the paths you already took",
            ["부엌에서 그릇 달그락 — 밥 시간"] = "Bowls clatter in the kitchen — feeding time",
            ["고양이가 밥 먹는 중 — 부엌만 피해"] = "The cat is eating — just avoid the kitchen",
            ["도감 등록!  {0}"] = "Codex entry!  {0}",
            ["할당량 채움! 이제 목적지에 모두 모이면 다음 스테이지"] = "Quota met! Gather everyone at the destination for the next stage",
            ["{0}가 들어왔어요"] = "{0} joined",
            ["풀려났다! 지금 도망쳐!"] = "Free! Run now!",
            ["끈끈이! 동료가 E로 구해 줘야 해요"] = "Glued! A teammate has to free you with E",
            ["찌릿! 잠깐 못 움직여요"] = "Zap! Can't move for a moment",
            ["잡혔다! A·D 번갈아 연타 = 버둥 — 보는 쪽으로 굴러간다"] = "Caught! Mash A·D to struggle — you roll the way you face",
            ["쓰러졌어요… 동료가 내 몸을 {0}으로 끌고 가면 살아나요\n[Q] 찍찍 = 동료에게 내 자리 알림 (고양이도 들어요)"] = "You're down… get dragged to {0} to revive\n[Q] squeak = call teammates (cats hear it)",
            ["살아났다! 다시 움직여요"] = "Revived! You can move again",
            ["{0}가 고양이에게 잡혔어요! 눈에 띄어 고양이를 떼어 내요\n{1}"] = "{0} was caught by a cat! Get its attention to pull it off\n{1}",
            ["{0}가 다운됐어요! {1}으로 옮겨 주세요\n{2}"] = "{0} is down! Carry them to {1}\n{2}",
            ["{0}가 끈끈이에 붙었어요! [E] 길게 눌러 구출\n{1}"] = "{0} is stuck on a glue trap! Hold [E] to free them\n{1}",
            ["{0}가 나갔어요"] = "{0} left",
            // 소리 자막·방향 (고양이 197)
            ["(배 꼬르륵 — 고양이가 밥 먹으러)"] = "(Tummy rumble — the cat heads to eat)",
            ["(모래 긁는 소리… 곧 우다다!)"] = "(Litter scratching… zoomies incoming!)",
            ["(창가 쪽 기지개 — 햇볕 쬐러)"] = "(A stretch by the window — off to sunbathe)",
            ["(쩌억 하품 — 자러 간다)"] = "(Big yawn — off to nap)",
            ["(할짝할짝 — 물 마시러)"] = "(Lap lap — off to drink)",
            ["(츄릅… 어디선가)"] = "(Slurp… from somewhere)",
            ["(냐앙! — 아기 고양이가 엄마를 부른다)"] = "(Mew! — a kitten calls for mom)",
            ["(쿨쿨… 문지기가 졸고 있다 — 지금!)"] = "(Zzz… the gatekeeper is dozing — now!)",
            ["(꾸벅꾸벅… 순찰꾼이 잠들었다 — 큰길이 빈다)"] = "(Nodding off… the patroller fell asleep — the main hall is clear)",
            ["(드르렁… 고양이가 깊이 잠들었다)"] = "(Snore… the cat is fast asleep)",
            ["(드르렁… 문지기가 깊이 잠들었다)"] = "(Snore… the gatekeeper is fast asleep)",
            ["(드르렁… 순찰꾼이 깊이 잠들었다)"] = "(Snore… the patroller is fast asleep)",
            ["(드르렁… 아기 고양이가 깊이 잠들었다)"] = "(Snore… the kitten is fast asleep)",
            ["(코골이가 멈췄다 — 곧 깬다!)"] = "(The snoring stopped — waking soon!)",
            ["(문지기 코골이가 멈췄다 — 곧 깬다!)"] = "(The gatekeeper stopped snoring — waking soon!)",
            ["(순찰꾼 코골이가 멈췄다 — 곧 깬다!)"] = "(The patroller stopped snoring — waking soon!)",
            ["(아기 고양이 코골이가 멈췄다 — 곧 깬다!)"] = "(The kitten stopped snoring — waking soon!)",
            ["(찍찍!) 쓰러진 {0} — 여기 있어요 · {1}"] = "(Squeak!) Downed {0} — over here · {1}",
            ["(찍찍!) {0} · {1}"] = "(Squeak!) {0} · {1}",
            ["앞"] = "ahead",
            ["오른쪽 앞"] = "ahead right",
            ["오른쪽"] = "right",
            ["오른쪽 뒤"] = "behind right",
            ["뒤"] = "behind",
            ["왼쪽 뒤"] = "behind left",
            ["왼쪽"] = "left",
            ["왼쪽 앞"] = "ahead left",
            ["(킁킁… 코가 아직 얼얼 — {0}초)"] = "(Sniff… nose still tingling — {0}s)",
            // 기지 목적지 게시판·계산대 (고양이 200)
            ["[E] 목적지"] = "[E] Destination",
            ["[E] 상점"] = "[E] Shop",
            ["고양이 기능 모음 — 한 판"] = "All the cat features — one round",
            ["무작위 부엌 — 한 판"] = "Random kitchen — one round",
            ["새 루프 · 5스테이지 · 식량 할당량 · 목적지 상점 · 엔딩"] = "New loop · 5 stages · food quota · destination shop · ending",
            // 호스트가 묶어 보내는 문장 — Loc.Pack/Unpack (고양이 202)
            ["{0} ×{1}"] = "{0} ×{1}",
            ["살 수 없어요"] = "Can't buy that",
            ["지금은 살 수 없어요"] = "Can't buy right now",
            ["{0} 샀어요 — 다음 맵 출발방에"] = "Bought {0} — waiting in the next map's start room",
            ["마지막 스테이지 — 다음 맵이 없어요"] = "Last stage — there's no next map",
            ["식량 부족 ({0} 필요)"] = "Not enough food ({0} needed)",
            ["없는 항목"] = "No such item",
            ["최대 레벨"] = "Max level",
            ["누계 부족 ({0} 필요)"] = "Not enough total ({0} needed)",
            ["{0} Lv{1}"] = "{0} Lv{1}",
            ["정원 초과 (최대 4명)"] = "Room is full (max 4)",
            ["게임 진행 중에는 참가할 수 없음 (로비에서만 합류)"] = "Can't join mid-game (join from the base)",
            ["다음 맵으로 이동 중 — 기지로 돌아오면 참가할 수 있어요"] = "Moving to the next map — you can join once they're back at base",
            ["호스트와 연결이 끊겨 메인 메뉴로 돌아왔어요."] = "Lost connection to the host — back at the main menu.",
            // 도전과제 (고양이 219)
            ["도전과제 달성!  {0}"] = "Achievement!  {0}",
            ["첫 이사"] = "First Move",
            ["귀환하거나 벽 속 스테이지를 하나 넘기기"] = "Make it home, or clear one stage inside the walls",
            ["계란 택배"] = "Egg Courier",
            ["한 판에 계란 3개를 깨지 않고 가져오기"] = "Bring home 3 unbroken eggs in one run",
            ["유령 쥐"] = "Ghost Rat",
            ["고양이에게 한 번도 쫓기지 않고 귀환하거나 스테이지 넘기기"] = "Get home or clear a stage without ever being chased",
            ["구급 쥐"] = "Medic Rat",
            ["쓰러진 동료를 10번 살리기"] = "Revive downed teammates 10 times",
            ["깊은 쥐"] = "Deep Rat",
            ["벽 속 스테이지 4에 닿기"] = "Reach stage 4 inside the walls",
            ["요리사의 적"] = "Chef's Nemesis",
            ["로스트치킨을 가져오기"] = "Bring home a roast chicken",
            ["혼자 살아남기"] = "Lone Survivor",
            ["혼자 연 방에서 귀환하거나 엔딩 보기"] = "Get home or see the ending in a solo room",
            ["수집가"] = "Collector",
            ["도감 15종 채우기"] = "Fill 15 codex entries",
        };
    }
}
