using System.Collections.Generic;

namespace RatGame.EditorTools
{
    /// <summary>임시(더미) 영어 번역 — 키는 한국어 원문. Localize Menus가 표에 넣는다(빈 칸만 채우고 덮지 않음).</summary>
    public static partial class LocalizationTools
    {
        private static readonly Dictionary<string, string> DummyEn = new()
        {
            // 메인 메뉴
            ["쥐도 새도 모르게"] = "Not Even a Mouse",
            ["1~4인 협동 은신 약탈"] = "1-4 player co-op stealth heist",
            ["호스트 시작"] = "Host Game",
            ["친구 방 참가"] = "Join Friend",
            ["설정"] = "Settings",
            ["종료"] = "Quit",
            ["배경 장면 자리\n쥐구멍 앞에서 쥐 4마리 대기 (아트 단계)"] = "Background scene placeholder\n4 mice waiting at the mousehole (art pass)",
            ["로컬 모드"] = "Local mode",
            ["로컬 모드 (같은 PC에서만 참가)"] = "Local mode (same PC only)",
            [" · 개발 빌드"] = " · dev build",
            ["기지를 여는 중…"] = "Opening the base…",
            ["호스트를 시작하지 못했어요. 이미 켜진 게임이 있는지 확인하세요."] = "Couldn't start hosting. Is another game already running?",
            ["친구가 보낸 초대를 수락하면 바로 들어가요.\n(Steam 친구 목록에서 \"게임 참가\"도 돼요)"] = "Accept a friend's invite to join.\n(\"Join Game\" in the Steam friends list works too)",
            ["기지에 접속하는 중…"] = "Connecting to the base…",
            ["접속을 시작하지 못했어요."] = "Couldn't start connecting.",
            ["호스트를 찾지 못했어요. 친구가 방을 열었는지 확인하세요."] = "Host not found. Did your friend open a room?",
            // 일시정지
            ["일시정지"] = "Paused",
            ["계속하기"] = "Resume",
            ["세션 나가기"] = "Leave Session",
            ["나가기"] = "Leave",
            ["취소"] = "Cancel",
            ["호스트가 나가면 친구들의 세션도 끝나요.\n메인 메뉴로 나갈까요?"] = "If the host leaves, everyone's session ends.\nReturn to main menu?",
            ["메인 메뉴로 나갈까요?\n친구들은 계속 플레이해요."] = "Return to main menu?\nYour friends keep playing.",
            ["Esc · 계속하기   (게임은 멈추지 않아요)"] = "Esc · Resume   (the game keeps running)",
            ["내가 연 방"] = "My room",
            ["친구 방"] = "Friend's room",
            ["명"] = " players",
            // 설정
            ["조작"] = "Controls",
            ["마우스 감도"] = "Mouse sensitivity",
            ["웅크리기"] = "Crouch",
            ["화면 흔들림"] = "Camera shake",
            ["화면"] = "Display",
            ["화면 모드"] = "Screen mode",
            ["해상도"] = "Resolution",
            ["언어"] = "Language",
            ["소리"] = "Audio",
            ["전체"] = "Master",
            ["효과음"] = "Effects",
            ["음악"] = "Music",
            ["보이스"] = "Voice",
            ["기본값"] = "Defaults",
            ["닫기"] = "Close",
            ["적용"] = "Apply",
            ["누르고 있기"] = "Hold",
            ["눌러서 전환"] = "Toggle",
            ["켬"] = "On",
            ["끔"] = "Off",
            ["전체 화면"] = "Fullscreen",
            ["테두리 없는 창"] = "Borderless",
            ["창 모드"] = "Windowed",
            ["기본값으로 바꿨어요. [적용]을 눌러야 저장돼요."] = "Reset to defaults. Press [Apply] to save.",
            ["적용했어요."] = "Applied.",
            ["[적용]을 누르면 언어가 바뀌어요."] = "Press [Apply] to change the language.",
            // 게임 중 HUD·패널 (고양이 189)
            ["[E] 도감"] = "[E] Codex",
            ["[E] 거울"] = "[E] Mirror",
            ["[E] 쥐 상점"] = "[E] Rat Shop",
            ["도감"] = "Codex",
            ["닫기 (E / Esc)"] = "Close (E / Esc)",
            ["금 감"] = "Cracked",
            ["<b>F1</b>  조작"] = "<b>F1</b>  Controls",
            ["벽 속 지도  <size=70%>(팀이 가 본 방 · 주황 = 목적지 · 금색 = 보물방 · 파란 선 = 배관)</size>"] = "Map of the walls  <size=70%>(rooms your team visited · orange = destination · gold = treasure room · blue line = pipe)</size>",
            ["수확"] = "Haul",
            ["들고 온 것"] = "Carried home",
            ["누계"] = "Total",
            ["오늘의 쥐들"] = "Today's rats",
            ["오늘의 일꾼"] = "Top worker",
            ["다운"] = "Down",
            ["새 도감"] = "New codex",
            ["거울 — 스킨·털 색"] = "Mirror — skins & fur color",
            ["털 색 팔레트"] = "Fur color palette",
            ["색상"] = "Hue",
            ["채도"] = "Saturation",
            ["밝기"] = "Brightness",
            ["이 색 입기"] = "Wear this color",
            ["쥐 상점"] = "Rat Shop",
            ["상점 — 다음 맵 준비"] = "Shop — prepare for the next map",
            ["사기"] = "Buy",
            // F1 조작 안내 (고양이 190)
            ["조작  <size=70%>(F1 닫기)</size>"] = "Controls  <size=70%>(F1 to close)</size>",
            ["이동"] = "Move",
            ["달리기"] = "Sprint",
            ["점프"] = "Jump",
            ["잡기 · 놓기"] = "Grab · drop",
            ["던지기 (누르고 있다 떼기)"] = "Throw (hold, then release)",
            ["상호작용 ([E] 안내가 뜨면)"] = "Interact (when an [E] prompt shows)",
            ["찍찍 (소리 남 · 쓰러져서도 됨)"] = "Squeak (makes noise · works while down)",
            ["핑"] = "Ping",
            ["킁킁 — 목적지·음식 냄새"] = "Sniff — destination & food scent",
            ["주머니 칸 고르기"] = "Pick pocket slot",
            ["지도 (벽 속, 누르고 있기)"] = "Map (in the walls, hold)",
            ["메뉴"] = "Menu",
            ["화면 읽기"] = "Reading the screen",
            ["고양이 위 <b>?</b> 의심(밑에 이유) · <b>!</b> 추격"] = "Above a cat: <b>?</b> suspicious (reason below) · <b>!</b> chasing",
            ["오른쪽 아래 — 내 소리 크기 · 냄새 남기는 중"] = "Bottom right — how loud you are · leaving scent",
            ["빨간 표시 — 위기인 동료(구해질 때까지)"] = "Red marker — teammate in trouble (until rescued)",
            ["위기 때"] = "When in trouble",
            ["쓰러짐 — 동료가 몸을 쥐구멍(창고)에 넣으면 삶"] = "Down — a teammate carries your body into the mousehole (storeroom)",
            ["끈끈이 — 동료가 옆에서 E 길게"] = "Glue trap — a teammate holds E next to you",
            ["F3  고양이 정보 · F4  확인 메뉴 (개발용)"] = "F3  cat info · F4  check menu (dev)",
            ["좌클릭"] = "LMB",
            ["우클릭"] = "RMB",
            ["휠클릭"] = "MMB",
            // 위 상태 막대 RunBar (고양이 191) — {0}은 숫자·이름 자리 (Loc.F)
            ["[Enter] 출발   누계 {0}"] = "[Enter] Depart   Total {0}",
            ["호스트 출발 대기   누계 {0}"] = "Waiting for host to depart   Total {0}",
            ["스테이지 {0}/{1}   식량 {2}/{3}"] = "Stage {0}/{1}   Food {2}/{3}",
            ["쥐구멍 {0}   누계 {1}"] = "Mousehole {0}   Total {1}",
            [" · 쓰러진 {0}명 두고 감"] = " · leaving {0} downed behind",
            ["다음으로"] = "Next",
            ["귀환 중"] = "Heading home",
            [" · 빈손"] = " · empty-handed",
            ["식량이 모자라요 — {0} 더 모아 창고에"] = "Not enough food — bring {0} more to the storeroom",
            ["창고에 모이면 다음으로   {0}/{1}"] = "Gather in the storeroom to move on   {0}/{1}",
            ["쥐구멍에 모이면 귀환   {0}/{1}"] = "Gather at the mousehole to go home   {0}/{1}",
            [" · 아직 빈손이에요"] = " · still empty-handed",
            ["할당량 채움! 창고에 모이면 다음 · 상점 돈 +{0}"] = "Quota met! Gather in the storeroom · shop money +{0}",
            ["   · 정전"] = "   · Blackout",
            ["   · 덫 대방출"] = "   · Trap sale",
            ["   · 간식 날"] = "   · Treat day",
            ["   · 집주인 외출"] = "   · Owner out",
            ["   · 분주한 집"] = "   · Busy house",
            ["   · 고양이 손님"] = "   · Cat guest",
            ["출발…"] = "Departing…",
            ["출발 발판에 모이면 출발   {0}/{1}"] = "Gather on the departure pad to go   {0}/{1}",
            ["   최고 스테이지 {0}"] = "   Best stage {0}",
            [" · 엔딩 {0}번"] = " · endings {0}",
            ["누계 {0}   목적지 {1}"] = "Total {0}   Destination {1}",
            ["창고"] = "Storeroom",
            ["부엌(생성)"] = "Kitchen (generated)",
            ["벽 속(생성)"] = "Inside the walls (generated)",
            // E 안내·운반 안내·숨기 (고양이 192) — 게임 물체가 Core의 Loc으로 번역
            ["목적지 바꾸기"] = "Change destination",
            ["끈 흔들기"] = "Wiggle string",
            ["상점"] = "Shop",
            ["거울"] = "Mirror",
            ["초인종 누르기"] = "Ring doorbell",
            ["먹기 (스태미나 회복)"] = "Eat (restores stamina)",
            ["문 닫기"] = "Close door",
            ["문 열기"] = "Open door",
            ["물그릇 엎기"] = "Tip over water bowl",
            ["{0}에서 나오기"] = "Leave {0}",
            ["{0}에 숨기"] = "Hide in {0}",
            ["구출하기 — {0}"] = "Rescue — {0}",
            [" (길게)"] = " (hold)",
            ["[좌클릭] 놓기"] = "[LMB] Let go",
            ["[좌클릭] 놓기   {0}으로 끌고 가면 살아나요 {1}/{2}"] = "[LMB] Let go   Drag to {0} to revive {1}/{2}",
            ["[좌클릭] 놓기   함께 드는 중 {0}/{1}"] = "[LMB] Let go   Carrying together {0}/{1}",
            ["[우클릭 떼기] 던지기   [좌클릭] 취소"] = "[Release RMB] Throw   [LMB] Cancel",
            ["[좌클릭] 내려놓기   [우클릭 홀드] 던지기"] = "[LMB] Put down   [Hold RMB] Throw",
            ["쓰러진 {0}"] = "Downed {0}",
            ["[좌클릭] 집기 — {0}"] = "[LMB] Grab — {0}",
            ["{0} — 자리 없음 ({1}/{2})"] = "{0} — no room ({1}/{2})",
            ["[좌클릭] 같이 들기 — {0} ({1}/{2})"] = "[LMB] Lift together — {0} ({1}/{2})",
            ["창고(주황 방)"] = "the storeroom (orange room)",
            ["쥐구멍"] = "the mousehole",
            ["숨죽여… 고양이가 코앞"] = "Hold your breath… the cat is right there",
            ["숨는 중 · [E] 나가기 (소리 남)"] = "Hiding · [E] Leave (makes noise)",
            // 쥐 색 이름·숨을 곳·물건 이름 (데이터)
            ["회색 쥐"] = "Gray rat",
            ["파랑 쥐"] = "Blue rat",
            ["초록 쥐"] = "Green rat",
            ["노랑 쥐"] = "Yellow rat",
            ["신발"] = "shoe",
            ["빈 상자"] = "empty box",
            ["장화"] = "boot",
            ["쓰러진 동료"] = "Downed teammate",
            ["바게트"] = "Baguette",
            ["병뚜껑"] = "Bottle cap",
            ["참치캔"] = "Tuna can",
            ["사탕"] = "Candy",
            ["치즈 조각"] = "Cheese slice",
            ["치즈 덩어리"] = "Cheese block",
            ["로스트치킨"] = "Roast chicken",
            ["동전"] = "Coin",
            ["크래커"] = "Cracker",
            ["계란"] = "Egg",
            ["포도알"] = "Grape",
            ["헤어볼"] = "Hairball",
            ["햄 덩어리"] = "Ham",
            ["젤리"] = "Jelly",
            ["전구"] = "Light bulb",
            ["스마트폰"] = "Smartphone",
            ["접시"] = "Plate",
            ["반지"] = "Ring",
            ["비누"] = "Soap",
            ["회중시계"] = "Pocket watch",
            ["수박 조각"] = "Watermelon slice",
        };
    }
}
